In [60]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

In [61]:
# 호텔 예약 데이터에서 필요한 날짜 추출
# 날씨 데이터는 현지 날짜가 유의미한 날씨이므로 실제 호텔 도착 날을 기준으로 함
df_hotel = pd.read_csv('../data/preprocessed/hotel_bookings.csv')

date_min = df_hotel['arrival_date'].min()
date_max = df_hotel['arrival_date'].max()

print(f'도착 날짜: {date_min} ~ {date_max}')

도착 날짜: 2015-07-01 ~ 2017-08-31

In [62]:
# 날씨 데이터 불러오기
df = pd.read_csv('../data/raw/weather.csv')
df.head()

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2015-07-01 00:00:00,19.9,17.6,23.9,2.3,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-07-02 00:00:00,20.7,16.2,25.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-07-03 00:00:00,21.2,16.0,25.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-07-04 00:00:00,23.2,19.2,28.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-07-05 00:00:00,21.8,17.8,26.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
# 데이터 정보
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    793 non-null    str
 1   tavg    786 non-null    float64
 2   tmin    793 non-null    float64
 3   tmax    793 non-null    float64
 4   prcp    793 non-null    float64
 5   snow    7 non-null      float64
 6   wdir    0 non-null      float64
 7   wspd    0 non-null      float64
 8   wpgt    0 non-null      float64
 9   pres    0 non-null      float64
 10  tsun    0 non-null      float64
dtypes: float64(10), str(1)
memory usage: 68.3 KB

In [64]:
# 날짜 데이터 타입 변경
df['date'] = pd.to_datetime(df['date'].str[:10], format='%Y-%m-%d')
df['date']

0     2015-07-01
1     2015-07-02
2     2015-07-03
3     2015-07-04
4     2015-07-05
         ...
788   2017-08-27
789   2017-08-28
790   2017-08-29
791   2017-08-30
792   2017-08-31
Name: date, Length: 793, dtype: datetime64[us]

In [65]:
df.describe()

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
count,793,786.000000,793.000000,793.000000,793.000000,7.000000,0.0,0.0,0.0,0.0,0.0
mean,2016-07-31 00:00:00,18.032697,14.404540,22.453594,1.655738,1.142857,NaN,NaN,NaN,NaN,NaN
min,2015-07-01 00:00:00,6.300000,3.100000,9.200000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN
25%,2016-01-15 00:00:00,14.100000,11.200000,17.300000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN
50%,2016-07-31 00:00:00,18.100000,14.800000,22.100000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN
75%,2017-02-14 00:00:00,21.700000,17.600000,27.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN
max,2017-08-31 00:00:00,31.400000,27.400000,39.400000,46.400000,2.000000,NaN,NaN,NaN,NaN,NaN
std,NaN,4.782786,4.093664,5.871384,4.875469,0.377964,NaN,NaN,NaN,NaN,NaN

In [66]:
# 결측치 확인
df.isna().sum()

date      0
tavg      7
tmin      0
tmax      0
prcp      0
snow    786
wdir    793
wspd    793
wpgt    793
pres    793
tsun    793
dtype: int64

In [67]:
# 결측치 처리
# tavg: 평균 기온 -----> tmin, tmax 평균값
# 평균 기온, 강수량 외 결측치가 포함된 열 삭제
missing_cols_drop = ['snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun']
missing_cols_fill = ['tavg']

df.drop(missing_cols_drop, axis=1, inplace=True)
df[missing_cols_fill[0]] = df[missing_cols_fill[0]].fillna(df[['tmin', 'tmax']].mean(axis=1))

df.isna().sum()

date    0
tavg    0
tmin    0
tmax    0
prcp    0
dtype: int64

In [68]:
# 파일 저장
df.to_csv('../data/preprocessed/weather.csv', index=False)