In [1]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

In [8]:
# 호텔 예약 데이터에서 필요한 날짜 추출
# 환율 데이터는 예약한 날짜와 실제 호텔 투숙 날짜의 차이가 유의미한 데이터 이므로 호텔 예약 데이터에서 예약 날짜와 도착 날짜 모두 필요
df_hotel = pd.read_csv('../data/preprocessed/hotel_bookings.csv')

r_date_min = df_hotel['reservation_date'].min()
r_date_max = df_hotel['reservation_date'].max()

a_date_min = df_hotel['arrival_date'].min()
a_date_max = df_hotel['arrival_date'].max()

print(f'타겟 날짜: {min(r_date_min, a_date_min)} ~ {max(r_date_max, a_date_max)}')

타겟 날짜: 2013-06-24 ~ 2017-08-31

In [9]:
# 호텔 예약 데이터에서 필요한 국가 추출
df_hotel['country'].unique()

<StringArray>
['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', 'ROU', 'NOR', 'OMN', 'ARG',
 ...
 'ATA', 'GTM', 'ASM', 'MRT', 'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO']
Length: 177, dtype: str

In [15]:
# 타겟 국가 줄이기
# 호텔 예약 데이터에서 국가별 최빈값 순으로 새로운 데이터프레임 생성
df_country = df_hotel['country'].value_counts().reset_index()
df_country

    country  count
0       PRT  48590
1       GBR  12129
2       FRA  10415
3       ESP   8568
4       DEU   7287
..      ...    ...
172     NCL      1
173     KIR      1
174     SDN      1
175     ATF      1
176     SLE      1

[177 rows x 2 columns]

In [18]:
# count 100 이상인 데이터로 추리기
df_country = df_country.loc[df_country['count'] > 100]

# percentage 추가
df_country['percentage'] = df_country['count'] / df_country['count'].sum() * 100

df_country

   country  count  percentage
0      PRT  48590   41.739683
1      GBR  12129   10.419029
2      FRA  10415    8.946672
3      ESP   8568    7.360066
4      DEU   7287    6.259664
5      ITA   3766    3.235062
6      IRL   3375    2.899186
7      BEL   2342    2.011820
8      BRA   2224    1.910456
9      NLD   2104    1.807374
10     USA   2097    1.801361
11     CHE   1730    1.486101
12      CN   1279    1.098684
13     AUT   1263    1.084940
14     SWE   1024    0.879634
15     CHN    999    0.858159
16     POL    919    0.789438
17     ISR    669    0.574683
18     RUS    632    0.542899
19     NOR    607    0.521424
20     ROU    500    0.429509
21     FIN    447    0.383981
22     DNK    435    0.373673
23     AUS    426    0.365942
24     AGO    362    0.310965
25     LUX    287    0.246538
26     MAR    259    0.222486
27     TUR    248    0.213036
28     HUN    230    0.197574
29     ARG    214    0.183830
30     JPN    197    0.169227
31     CZE    171    0.146892
32     IND    152    0.130571
33     KOR    133    0.114249
34     GRC    128    0.109954
35     DZA    103    0.088479
36     SRB    101    0.086761

In [19]:
df_country['country'].unique()

<StringArray>
['PRT', 'GBR', 'FRA', 'ESP', 'DEU', 'ITA', 'IRL', 'BEL', 'BRA', 'NLD', 'USA',
 'CHE',  'CN', 'AUT', 'SWE', 'CHN', 'POL', 'ISR', 'RUS', 'NOR', 'ROU', 'FIN',
 'DNK', 'AUS', 'AGO', 'LUX', 'MAR', 'TUR', 'HUN', 'ARG', 'JPN', 'CZE', 'IND',
 'KOR', 'GRC', 'DZA', 'SRB']
Length: 37, dtype: str

In [ ]:
# 환율 데이터 불러오기
df = pd.read_csv('../data/raw/exchange_rates.csv')
df.head()

In [ ]:
# 데이터 정보
df.info()

In [ ]:
df.describe()

In [ ]:
# 결측치 확인
df.isna().sum()